import 'weather_data.dart';

class Autogenerated {
  String? message;
  String? cod;
  int? count;
  List<WeatherData>? list;

  Autogenerated({this.message, this.cod, this.count, this.list});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    message = json['message'];
    cod = json['cod'];
    count = json['count'];
    if (json['list'] != null) {
      list = <WeatherData>[];
      json['list'].forEach((v) {
        list!.add(new WeatherData.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['message'] = this.message;
    data['cod'] = this.cod;
    data['count'] = this.count;
    if (this.list != null) {
      data['list'] = this.list!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}