// weather_state.dart
import 'package:final_application/models/autogenerated.dart';

abstract class WeatherState {
  
}

class WeatherInitial extends WeatherState {
  WeatherInitial();
}

class WeatherLoading extends WeatherState {
  WeatherLoading();
}

class WeatherLoaded extends WeatherState {
  final Autogenerated weatherData;
  
  WeatherLoaded(this.weatherData);
}

class WeatherError extends WeatherState {
  final String message;
  
  WeatherError(this.message);
}