import 'package:http/http.dart' as http;
import 'dart:convert';
import '../models/autogenerated.dart'; 

class OpenWeatherAPI {
  static const String apiKey = '26baf8c9b29c26fba795c65511bf399e'; 
  static const String baseUrl = 'https://api.openweathermap.org/data/2.5';

  Future<Autogenerated> getWeather(String cityName) async {
    final response = await http.get(Uri.parse(
      '$baseUrl/find?q=$cityName&appid=$apiKey&units=metric&lang=ru'));

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Ошибка загрузки данных: ${response.statusCode}');
    }
  }

  
  Future<Autogenerated> getWeatherByCoordinates(double lat, double lon) async {
    final response = await http.get(Uri.parse(
      '$baseUrl/find?lat=$lat&lon=$lon&appid=$apiKey&units=metric&lang=ru'));

    if (response.statusCode == 200) {
      return Autogenerated.fromJson(json.decode(response.body));
    } else {
      throw Exception('Ошибка загрузки данных: ${response.statusCode}');
    }
  }
}
